// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: api/v1/process_runner.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Process state
type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNSPECIFIED ProcessState = 0
	ProcessState_PROCESS_STATE_RUNNING     ProcessState = 1
	ProcessState_PROCESS_STATE_STOPPED     ProcessState = 2
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_RUNNING",
		2: "PROCESS_STATE_STOPPED",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED": 0,
		"PROCESS_STATE_RUNNING":     1,
		"PROCESS_STATE_STOPPED":     2,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_process_runner_proto_enumTypes[0].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_api_v1_process_runner_proto_enumTypes[0]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{0}
}

type GetOutputResponse_Type int32

const (
	GetOutputResponse_TYPE_UNSPECIFIED GetOutputResponse_Type = 0
	GetOutputResponse_TYPE_STDOUT      GetOutputResponse_Type = 1
	GetOutputResponse_TYPE_STDERR      GetOutputResponse_Type = 2
)

// Enum value maps for GetOutputResponse_Type.
var (
	GetOutputResponse_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_STDOUT",
		2: "TYPE_STDERR",
	}
	GetOutputResponse_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_STDOUT":      1,
		"TYPE_STDERR":      2,
	}
)

func (x GetOutputResponse_Type) Enum() *GetOutputResponse_Type {
	p := new(GetOutputResponse_Type)
	*p = x
	return p
}

func (x GetOutputResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetOutputResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_process_runner_proto_enumTypes[1].Descriptor()
}

func (GetOutputResponse_Type) Type() protoreflect.EnumType {
	return &file_api_v1_process_runner_proto_enumTypes[1]
}

func (x GetOutputResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetOutputResponse_Type.Descriptor instead.
func (GetOutputResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{7, 0}
}

type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command to execute
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Command arguments
	Args          []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_api_v1_process_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StartResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProcessIdentifier string                 `protobuf:"bytes,1,opt,name=process_identifier,json=processIdentifier,proto3" json:"process_identifier,omitempty"`
	Status            *ProcessStatus         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_api_v1_process_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetProcessIdentifier() string {
	if x != nil {
		return x.ProcessIdentifier
	}
	return ""
}

func (x *StartResponse) GetStatus() *ProcessStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProcessIdentifier string                 `protobuf:"bytes,1,opt,name=process_identifier,json=processIdentifier,proto3" json:"process_identifier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_v1_process_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetProcessIdentifier() string {
	if x != nil {
		return x.ProcessIdentifier
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *Process               `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Status        *ProcessStatus         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_v1_process_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *StatusResponse) GetStatus() *ProcessStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProcessIdentifier string                 `protobuf:"bytes,1,opt,name=process_identifier,json=processIdentifier,proto3" json:"process_identifier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_v1_process_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetProcessIdentifier() string {
	if x != nil {
		return x.ProcessIdentifier
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *Process               `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Status        *ProcessStatus         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_v1_process_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *StopResponse) GetStatus() *ProcessStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetOutputRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProcessIdentifier string                 `protobuf:"bytes,1,opt,name=process_identifier,json=processIdentifier,proto3" json:"process_identifier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOutputRequest) Reset() {
	*x = GetOutputRequest{}
	mi := &file_api_v1_process_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutputRequest) ProtoMessage() {}

func (x *GetOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutputRequest.ProtoReflect.Descriptor instead.
func (*GetOutputRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{6}
}

func (x *GetOutputRequest) GetProcessIdentifier() string {
	if x != nil {
		return x.ProcessIdentifier
	}
	return ""
}

// Chunk of the output
type GetOutputResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the stream
	Type GetOutputResponse_Type `protobuf:"varint,1,opt,name=type,proto3,enum=api.v1.GetOutputResponse_Type" json:"type,omitempty"`
	// Binary chunk of the stream
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // gRPC streaming guarantees ordering, so don't need any chunk numeration on this level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutputResponse) Reset() {
	*x = GetOutputResponse{}
	mi := &file_api_v1_process_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutputResponse) ProtoMessage() {}

func (x *GetOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutputResponse.ProtoReflect.Descriptor instead.
func (*GetOutputResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{7}
}

func (x *GetOutputResponse) GetType() GetOutputResponse_Type {
	if x != nil {
		return x.Type
	}
	return GetOutputResponse_TYPE_UNSPECIFIED
}

func (x *GetOutputResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Process id and status
type Process struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command that was used to start the process
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Command arguments
	Args          []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_api_v1_process_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{8}
}

func (x *Process) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Process) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Status of a process
type ProcessStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ProcessState           `protobuf:"varint,1,opt,name=state,proto3,enum=api.v1.ProcessState" json:"state,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	mi := &file_api_v1_process_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_process_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatus.ProtoReflect.Descriptor instead.
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_process_runner_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessStatus) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *ProcessStatus) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ProcessStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProcessStatus) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

var File_api_v1_process_runner_proto protoreflect.FileDescriptor

const file_api_v1_process_runner_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/v1/process_runner.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\fStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"m\n" +
	"\rStartResponse\x12-\n" +
	"\x12process_identifier\x18\x01 \x01(\tR\x11processIdentifier\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x15.api.v1.ProcessStatusR\x06status\">\n" +
	"\rStatusRequest\x12-\n" +
	"\x12process_identifier\x18\x01 \x01(\tR\x11processIdentifier\"j\n" +
	"\x0eStatusResponse\x12)\n" +
	"\aprocess\x18\x01 \x01(\v2\x0f.api.v1.ProcessR\aprocess\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x15.api.v1.ProcessStatusR\x06status\"<\n" +
	"\vStopRequest\x12-\n" +
	"\x12process_identifier\x18\x01 \x01(\tR\x11processIdentifier\"h\n" +
	"\fStopResponse\x12)\n" +
	"\aprocess\x18\x01 \x01(\v2\x0f.api.v1.ProcessR\aprocess\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x15.api.v1.ProcessStatusR\x06status\"A\n" +
	"\x10GetOutputRequest\x12-\n" +
	"\x12process_identifier\x18\x01 \x01(\tR\x11processIdentifier\"\x9b\x01\n" +
	"\x11GetOutputResponse\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.api.v1.GetOutputResponse.TypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\">\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_STDOUT\x10\x01\x12\x0f\n" +
	"\vTYPE_STDERR\x10\x02\"7\n" +
	"\aProcess\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\xdd\x01\n" +
	"\rProcessStatus\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.api.v1.ProcessStateR\x05state\x12 \n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTimeB\f\n" +
	"\n" +
	"_exit_code*c\n" +
	"\fProcessState\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15PROCESS_STATE_STOPPED\x10\x022\xfc\x01\n" +
	"\x14ProcessRunnerService\x124\n" +
	"\x05Start\x12\x14.api.v1.StartRequest\x1a\x15.api.v1.StartResponse\x127\n" +
	"\x06Status\x12\x15.api.v1.StatusRequest\x1a\x16.api.v1.StatusResponse\x121\n" +
	"\x04Stop\x12\x13.api.v1.StopRequest\x1a\x14.api.v1.StopResponse\x12B\n" +
	"\tGetOutput\x12\x18.api.v1.GetOutputRequest\x1a\x19.api.v1.GetOutputResponse0\x01B6Z4github.com/SanjoDeundiak/process-runner/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_process_runner_proto_rawDescOnce sync.Once
	file_api_v1_process_runner_proto_rawDescData []byte
)

func file_api_v1_process_runner_proto_rawDescGZIP() []byte {
	file_api_v1_process_runner_proto_rawDescOnce.Do(func() {
		file_api_v1_process_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_process_runner_proto_rawDesc), len(file_api_v1_process_runner_proto_rawDesc)))
	})
	return file_api_v1_process_runner_proto_rawDescData
}

var file_api_v1_process_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_process_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_process_runner_proto_goTypes = []any{
	(ProcessState)(0),             // 0: api.v1.ProcessState
	(GetOutputResponse_Type)(0),   // 1: api.v1.GetOutputResponse.Type
	(*StartRequest)(nil),          // 2: api.v1.StartRequest
	(*StartResponse)(nil),         // 3: api.v1.StartResponse
	(*StatusRequest)(nil),         // 4: api.v1.StatusRequest
	(*StatusResponse)(nil),        // 5: api.v1.StatusResponse
	(*StopRequest)(nil),           // 6: api.v1.StopRequest
	(*StopResponse)(nil),          // 7: api.v1.StopResponse
	(*GetOutputRequest)(nil),      // 8: api.v1.GetOutputRequest
	(*GetOutputResponse)(nil),     // 9: api.v1.GetOutputResponse
	(*Process)(nil),               // 10: api.v1.Process
	(*ProcessStatus)(nil),         // 11: api.v1.ProcessStatus
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_api_v1_process_runner_proto_depIdxs = []int32{
	11, // 0: api.v1.StartResponse.status:type_name -> api.v1.ProcessStatus
	10, // 1: api.v1.StatusResponse.process:type_name -> api.v1.Process
	11, // 2: api.v1.StatusResponse.status:type_name -> api.v1.ProcessStatus
	10, // 3: api.v1.StopResponse.process:type_name -> api.v1.Process
	11, // 4: api.v1.StopResponse.status:type_name -> api.v1.ProcessStatus
	1,  // 5: api.v1.GetOutputResponse.type:type_name -> api.v1.GetOutputResponse.Type
	0,  // 6: api.v1.ProcessStatus.state:type_name -> api.v1.ProcessState
	12, // 7: api.v1.ProcessStatus.start_time:type_name -> google.protobuf.Timestamp
	12, // 8: api.v1.ProcessStatus.end_time:type_name -> google.protobuf.Timestamp
	2,  // 9: api.v1.ProcessRunnerService.Start:input_type -> api.v1.StartRequest
	4,  // 10: api.v1.ProcessRunnerService.Status:input_type -> api.v1.StatusRequest
	6,  // 11: api.v1.ProcessRunnerService.Stop:input_type -> api.v1.StopRequest
	8,  // 12: api.v1.ProcessRunnerService.GetOutput:input_type -> api.v1.GetOutputRequest
	3,  // 13: api.v1.ProcessRunnerService.Start:output_type -> api.v1.StartResponse
	5,  // 14: api.v1.ProcessRunnerService.Status:output_type -> api.v1.StatusResponse
	7,  // 15: api.v1.ProcessRunnerService.Stop:output_type -> api.v1.StopResponse
	9,  // 16: api.v1.ProcessRunnerService.GetOutput:output_type -> api.v1.GetOutputResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v1_process_runner_proto_init() }
func file_api_v1_process_runner_proto_init() {
	if File_api_v1_process_runner_proto != nil {
		return
	}
	file_api_v1_process_runner_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_process_runner_proto_rawDesc), len(file_api_v1_process_runner_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_process_runner_proto_goTypes,
		DependencyIndexes: file_api_v1_process_runner_proto_depIdxs,
		EnumInfos:         file_api_v1_process_runner_proto_enumTypes,
		MessageInfos:      file_api_v1_process_runner_proto_msgTypes,
	}.Build()
	File_api_v1_process_runner_proto = out.File
	file_api_v1_process_runner_proto_goTypes = nil
	file_api_v1_process_runner_proto_depIdxs = nil
}
